#   Copyright (c) 2023 Alan Chandler, all rights reserved
#
#   This file is part of AKCMoney.
#
#   AKCMoney is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   AKCMoney is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with AKCMoney.  If not, see <http://www.gnu.org/licenses/>.
#
services:
  moneyclient:
    image: docker.chandlerfamily.org.uk/moneyclient
    container_name: moneyclient
    ports: 
      - 6080:80

    restart: unless-stopped
    depends_on:
      - moneyserver
  moneyserver:
    image: docker.chandlerfamily.org.uk/moneyserver
    container_name: moneyserver
    ports: 
      - 2010:2010
    restart: unless-stopped
    volumes:
      - "/volume1/docker/money/db"
    tty: true
