# syntax=docker/dockerfile:1.0-experimental
#
#   Copyright (c) 2025 Alan Chandler, all rights reserved
#
#   This file is part of AKCMoney.
#
#   AKCMoney is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   AKCMoney is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with AKCMoney.  If not, see <http://www.gnu.org/licenses/>.
#

FROM nginx:mainline-alpine-slim 
LABEL uk.org.chandlerfamily.maintainer="Alan Chandler <alan@chandlerfamily.org.uk>"
COPY nginx/default.conf /etc/nginx/conf.d/